# presidio_governance/rehydrator.py

from typing import Dict
from utils.logger import logger


class PresidioRehydrator:
    """Re-hydrates anonymized session tokens back into real PII values."""

    def rehydrate_text(self, anonymized_text: str, token_map: Dict[str, str]) -> str:
        """
        Replaces anonymized tokens with real PII values for authorized end-user display.
        
        Args:
            anonymized_text: Response text generated by LLM/Agent containing tokens.
            token_map: Dictionary mapping tokens to real raw values.
            
        Returns:
            Re-hydrated string with original values restored.
        """
        if not anonymized_text or not token_map:
            return anonymized_text

        rehydrated = anonymized_text
        rehydrated_count = 0

        # Replace each token back with its real value
        for token, real_val in token_map.items():
            if token in rehydrated:
                rehydrated = rehydrated.replace(token, real_val)
                rehydrated_count += 1

        logger.info(f"[PRESIDIO] Re-hydrated {rehydrated_count} tokens back into real user context.")
        return rehydrated


# Instantiate global rehydrator service
presidio_rehydrator_service = PresidioRehydrator()